(()=>{const RV='v2026.09.23-01',BY_PNU=new Map(),BY_LOC=new Map(),BY_NAME=new Map();let ready=false,promise=null;
function norm(s){return String(s||'').trim().replace(/^경상남도\s*진주시\s*/,'').replace(/번지\s*$/,'').replace(/\s+/g,'').toLowerCase()}
function push(m,k,r){if(!k)return;if(!m.has(k))m.set(k,[]);m.get(k).push(r)}
function first(p,ks){for(const k of ks){const v=p?.[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim()}return''}
async function loadReg(){if(ready)return;if(promise)return promise;promise=(async()=>{try{if(typeof message==='function')message('건축물대장 높이·층수 정보 불러오는 중…');const idx=await fetch('data/register/index.json?v=20260923-1',{cache:'no-store'}).then(r=>r.json());const parts=await Promise.all(idx.parts.map(f=>fetch(f+'?v=20260923-1',{cache:'no-store'}).then(r=>r.json())));for(const part of parts)for(const r of part.records||[]){push(BY_PNU,String(r[0]||''),r);push(BY_LOC,norm(r[1]),r);const n=norm(r[5]);if(n)push(BY_NAME,n,r);const d=norm(r[6]);if(n&&d)push(BY_NAME,n+d,r)}ready=true;return idx}catch(e){promise=null;console.warn('register load failed',e);throw e}})();return promise}
function choose(p){if(!ready||!p)return null;const a=[],seen=new Set(),add=x=>{for(const r of x||[]){const k=r[0]+'|'+r[5]+'|'+r[6]+'|'+r[2]+'|'+r[3];if(!seen.has(k)){seen.add(k);a.push(r)}}};const pnu=first(p,['pnu','PNU','pnu_cd','PNU_CD','lot_pnu','LOT_PNU']);if(/^\d{19}$/.test(pnu))add(BY_PNU.get(pnu));const legal=first(p,['legal_name','bjd_name','BJD_NAM','emd_nm','EMD_NM','법정동명']),jibun=first(p,['jibun','JIBUN','lotno','LOTNO','지번']);if(legal&&jibun)add(BY_LOC.get(norm(legal+jibun)));else if(jibun)add(BY_LOC.get(norm(jibun)));const bn=first(p,['building_name','name','NAME','bld_nm','BLD_NM','건물명']);if(bn)add(BY_NAME.get(norm(bn)));if(!a.length)return null;if(a.length===1)return a[0];const nn=norm(bn),un=norm(first(p,['use_name','building','class','용도']));let best=null,bs=-1;for(const r of a){let s=0,rn=norm(r[5]),rd=norm(r[6]),ru=norm(r[7]);if(nn&&rn&&(nn===rn||nn.includes(rn)||rn.includes(nn)))s+=5;if(nn&&rd&&nn.includes(rd))s+=3;if(un&&ru&&(un.includes(ru)||ru.includes(un)))s+=1;if(Number(r[2])>0)s+=.2;if(s>bs){bs=s;best=r}}if(bs>=3)return best;const sig=new Set(a.map(r=>(Number(r[2])||0)+'|'+(Number(r[3])||0)));return sig.size===1?a[0]:null}
function apply(fc){let matched=0,rh=0,rf=0,high=0,mid=0,low=0;for(const f of fc.features||[]){const p=f.properties||{},r=choose(p);if(r){matched++;const h=Number(r[2])||0,fl=Number(r[3])||0;if(fl>0){p.floors_above=fl;rf++}if(h>0){p.render_height=h;p.height_confidence='높음';p.height_source='건축물대장 실제 높이';rh++}else if(fl>0&&!(Number(p.height_m)>0)){p.render_height=fl*floorHeight(r[7]||p.use_name||'');p.height_confidence='보통';p.height_source='건축물대장 '+fl+'층 기반 추정'}p.register_match=true;p.register_name=r[5]||'';p.register_dong=r[6]||''}if(p.height_confidence==='높음')high++;else if(p.height_confidence==='보통')mid++;else low++}fc._heightStats={...(fc._heightStats||{}),high,mid,low,registerMatched:matched,registerHeight:rh,registerFloors:rf};return fc}
function inject(){document.title=document.title.replace(/v\d{4}\.\d{2}\.\d{2}-\d+/,RV);document.querySelectorAll('.version').forEach(x=>x.textContent=RV);const top=document.querySelector('.top p');if(top)top.textContent='건축물대장 높이 보정 + GIS/OSM 자동 병합 + 선택형 VWorld';const st=document.querySelector('.status');if(st&&!document.getElementById('sRegister')){const a=document.createElement('span');a.textContent='건축물대장 보정';const b=document.createElement('strong');b.id='sRegister';b.textContent='-';st.append(a,b)}}
function install(){inject();const on=window.normalizeBuildings;if(typeof on==='function')window.normalizeBuildings=function(fc){const x=on(fc);return ready?apply(x):x};const oo=window.osm3dInfo;if(typeof oo==='function')window.osm3dInfo=function(p){const r=choose(p);if(r){const h=Number(r[2])||0,fl=Number(r[3])||0;if(h>1)return{height:Math.min(h,350),has:true,source:'건축물대장 실제 높이'};if(fl>0)return{height:Math.min(fl*floorHeight(r[7]||''),350),has:true,source:'건축물대장 '+fl+'층'}}return oo(p)};const os=window.selectDistrict;if(typeof os==='function')window.selectDistrict=async function(id){try{await loadReg()}catch(e){}const v=await os(id);const s=window.currentBuildings?._heightStats;if(s&&document.getElementById('sRegister'))document.getElementById('sRegister').textContent=(s.registerMatched||0).toLocaleString()+'개 매칭 · 실제높이 '+(s.registerHeight||0).toLocaleString()+'개';return v};loadReg().catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();})();